# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: windows-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

- task: SynopsysDetectTask@9
  inputs:
    BlackDuckService: 'Blackduck-Azure'
    DetectArguments: |
      --detect.project.name=CarOffers
      --detect.project.version.name=Azure-Devops
      --detect.code.location.name=CarOffers_Azure-Devops
      --blackduck.trust.cert=true
    DetectVersion: 'latest'