# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: bash <(curl -s -L https://detect.synopsys.com/detect7.sh) --blackduck.url=https://52.29.53.171/ --blackduck.api.token=NmMyODRhMTYtZTI1OC00N2U0LWEyMTYtNTFkNDEzZmY2MzljOmU5ZDZjMWViLTMyMjctNDg4Yi05OGY0LWEyOGZmODdmMTVmOA== --detect.project.name=Sixt_GithubActions --detect.project.version.name=0.1 --blackduck.trust.cert=true
