# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Blackduck-Scan [PR]

on:
  push:
    # branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    #- run: npm run build --if-present
    #- run: npm test
    
    - name: Run Synopsys Detect
      uses: synopsys-sig/detect-action@v0.3.0
      with:
          github-token: ${{ secrets.GITHUB_TOKEN}}
          detect-version: 8.10.0
          blackduck-url: ${{ secrets.BD_URL }}
          blackduck-api-token: ${{ secrets.BD_TOKEN}}
